### ISSUE TITLE
custom conversation loading/previewer window gone?

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#25]
The nifty custom loading/previewing window seems to be gone, I can't find it.

'view archived conversations' just opens a normal file browser now. Since archives.js still exists, this might not be intentional?

**Comment by SparksJ2** [comment]
Oh, it's under the 'Conversations' menu now. Or was it always there? My bad. Bit confusing, though.

**Comment by sorentycho** [comment]
Since it's conversation-specific (and electron's pathological OS-level menu support makes adding non-global menu items inconvenient). I'll probably move it back if I ever come up with an elegant way of doing menus in Electron.

...actually in general a lot of the menu related bugs are due to the combination of Electron's Mac-centricism with the stupid way menus work on MacOS.
