### ISSUE TITLE
Windows + utility script.

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#27]
`The Commit menu item is a convenience for executing a script named commit in your conversations directory.`

I put a batch file named 'commit' (also tried 'commit.bat') in there, but it's not doing anything. Windows will probably need a different technique here than Linux.

https://stackoverflow.com/questions/42985964/run-a-bat-file-from-javascript

**Comment by sorentycho** [comment]
Curious. If you run the source version from a command prompt, do you get any error output when trying this? Does Windows have a weird way of setting +x on scripts?

I'm afraid this is probably a WONTFIX if I'd have to maintain OS-detecting code paths, since I have no way of developing the windows version. :-(

**Comment by SparksJ2** [comment]
>If you run the source version from a command prompt, do you get any error output when trying this?
Negative.
>Does Windows have a weird way of setting +x on scripts?
No such concept in windows, it's by file extension.
>I'm afraid this is probably a WONTFIX if I'd have to maintain OS-detecting code paths, since I have no way of developing the windows version. :-(
Hmm. It's fairly simple, 2 short lines, let me attach this again:

https://stackoverflow.com/questions/42985964/run-a-bat-file-from-javascript

**Comment by sorentycho** [comment]
Ah, but that's Windows Script Host, not node, which doesn't have that API. Now, I could do hack where I use node's `child_process` module to invoke a WSH script from the filesystem and then...funny, something seems wrong with that idea? :)

Anyway, I *think* the real problem was needing to specify `shell: true` in the `spawn` arguments. I'm about to push a version that hopefully fixes this, but if not I'll just drop the feature - I keep almost hacking it out in favor of a keybind in my hotkey daemon instead anyway, since that's all this really is.

**Comment by SparksJ2** [comment]
Ah-ha! That worked! It's just silent... my `echo hello world` script never appeared because there is no window popping up even for an instant. It may have worked the last time, not sure. But I was able to get `copy file1.txt file2.txt` to copy a file, so that's great.

The file does have to have the `.bat` extension.
